// Action Types

//burger-constructor.js
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';
// export const SET_INGREDIENT = 'SET_INGREDIENT';
// export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

//ingredient-details.js
export const ADD_CURRENT_INGREDIENT = 'ADD_CURRENT_INGREDIENT';
export const CLEAR_CURRENT_INGREDIENT = 'CLEAR_CURRENT_INGREDIENT';

//ingredients.js
export const INGREDIENTS_REQUEST = 'INGREDIENTS_REQUEST';
export const INGREDIENTS_LOADING = 'INGREDIENTS_LOADING';
export const INGREDIENTS_LOAD_SUCCESS = 'INGREDIENTS_LOAD_SUCCESS';
export const INGREDIENTS_LOAD_ERROR = 'INGREDIENTS_LOAD_ERROR';

//order-details.js
export const ORDER_LOADING = 'ORDER_LOADING';
export const ORDER_LOAD_SUCCESS = 'ORDER_LOAD_SUCCESS';
export const ORDER_LOAD_ERROR = 'ORDER_LOAD_ERROR';
export const ORDER_NUMBER_UPDATE = 'ORDER_NUMBER_UPDATE'; // как это сделать? очистить полность бургер конструктор?! и номер заказа?

//auth.js
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN = 'LOGIN';

export const LOGOUT = 'LOGOUT';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED = 'REFRESH_TOKEN_FAILED';

export const GET_USER = 'GET_USER';

export const UPDATE_USER = 'UPDATE_USER';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';



