// Action Types

//burger-constructor.js
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';
// export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

//ingredient-details.js
// export const INCREASE_INGREDIENT = 'INCREASE_INGREDIENT';
// export const DECREASE_INGREDIENT = 'DECREASE_INGREDIENT'; 
// export const UPDATE_CONSTRUCTOR = 'UPDATE_CONSTRUCTOR';

//ingredients.js
export const INGREDIENTS_REQUEST = 'INGREDIENTS_REQUEST';
export const INGREDIENTS_LOADING = 'INGREDIENTS_LOADING';
export const INGREDIENTS_LOAD_SUCCESS = 'INGREDIENTS_LOAD_SUCCESS';
export const INGREDIENTS_LOAD_ERROR = 'INGREDIENTS_LOAD_ERROR';

//order-details.js
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_LOADING = 'ORDER_LOADING';
export const ORDER_LOAD_SUCCESS = 'ORDER_LOAD_SUCCESS';
export const ORDER_LOAD_ERROR = 'ORDER_LOAD_ERROR';
// export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
// export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
// export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';
// export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
// export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
// export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
// CLEAR_ORDER, 
// GET_ORDER, 
// GET_ORDER_FAILED, 
// GET_ORDER_SUCCESS, 
// ORDER_LOAD
//fetch orders
// export const FETCH_ORDER = 'FETCH_ORDERS';
// export const FETCH_ORDER_REQUEST = 'FETCH_ORDERS_REQUEST';
// export const FETCH_ORDER_SUCCESS = 'FETCH_ORDERS_SUCCESS';
// export const FETCH_ORDER_FAILURE = 'FETCH_ORDERS_FAILURE';
//request.js
// export const FETCH_INGREDIENTS_FAILURE = 'FETCH_INGREDIENTS_FAILURE';


