// Action Types

//burger-constructor.js
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';

//ingredient-details.js
export const ADD_CURRENT_INGREDIENT = 'ADD_CURRENT_INGREDIENT';
export const CLEAR_CURRENT_INGREDIENT = 'CLEAR_CURRENT_INGREDIENT';

//ingredients.js
export const INGREDIENTS_REQUEST = 'INGREDIENTS_REQUEST';
export const INGREDIENTS_LOADING = 'INGREDIENTS_LOADING';
export const INGREDIENTS_LOAD_SUCCESS = 'INGREDIENTS_LOAD_SUCCESS';
export const INGREDIENTS_LOAD_ERROR = 'INGREDIENTS_LOAD_ERROR';

//order-details.js
export const ORDER_LOADING = 'ORDER_LOADING';
export const ORDER_LOAD_SUCCESS = 'ORDER_LOAD_SUCCESS';
export const ORDER_LOAD_ERROR = 'ORDER_LOAD_ERROR';

//auth.js
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_EMAIL_SUBMITTED = 'SET_EMAIL_SUBMITTED';




